[phases.setup]
nixPkgs = [
  "nodejs_20",
  "yarn-1_x"
]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "serve -s build -l tcp://0.0.0.0:3000"