export const microDA = {
    "B11" : "DatiAnagraficiDenominazione",
    "B13" : "",
    "B12" : "DatiAnagraficiCodiceCciaa",
    "B14" : "DatiAnagraficiSede",
    "B15" : "DatiAnagraficiPartitaIva",
    "B16" : "DatiAnagraficiCapitaleSociale",
    "B17" : "startDate",
    "B18" : "",
    "B19" : "",
    "B20" : "",
    "B21" : "",
    "B22" : "",
    "B23" : "",
    "B24" : "TotaleDipendentiNumeroMedio",
    "B25" : "DatiAnagraficiAppartenenzaGruppo",
    "B26" : ""
}

export const microB = {
    "B6":"CreditiVersoSociVersamentiAncoraDovutiParteRichiamare",
    "B7":"CreditiVersoSociVersamentiAncoraDovutiParteRichiamare",
    "B54":"",
    "B55":"",
    "B56":"",
    "B30":"",
    "B52":"",
    "B59":"",
    "B60":"",
    "B61":"",
    "B62":"",
    "B63":"",
    "B203":"",
    "B204":"",
    "B80":"",
    "B86":"",
    "B87":"",
    "B88":"",
    "B89":"",
    "B90":"",
    "B117":"",
    "B118":"",
    "B119":"",
    "B120":"",
    "B121":"",
    "B122":"TotaleProventiOneriFinanziari",
    "B123":"",
    "B125":"",
    "B126":"",
    "B127":"",
    "B129":"",
    "B130":"",
    "B133":"",
    "B134":"",
    "B135":"",
    "B136":"PatrimonioNettoRiservaLegale",
    "B137":"",
    "B138":"",
    "B140":"",
    "B141":"PatrimonioNettoCapitale",
    "B142":"",
    "B143":"",
    "B144":"",
    "B145":"",
    "B146":"",
    "B147":"",
    "B148":"",
    "B149":"",
    "B150":"",
    "B151":"PatrimonioNettoUtiliPerditePortatiNuovo",
    "B154":"",
    "B155":"",
    "B156":"",
    "B157":"",
    "B158":"",
    "B206":"",
    "B207":"",
    "B209":"",
    "B211":"",
    "B212":"",
    "B213":"",
    "B214":"",
    "B216":"",
    "B217":"",
    "B218":"",
    "B219":"",
    "B221":"ValoreProduzioneRicaviVenditePrestazioni",
    "B222":"",
    "B223":"",
    "B224":"",
    "B226":"",
    "B227":"CostiProduzioneServizi",
    "B229":"",
    "B230":"",
    "B231":"",
    "B233":"",
    "B234":"",
    "B235":"",
    "B236":"",
    "B237":"",
    "B239":"CostiProduzioneAmmortamentiSvalutazioniAmmortamentoImmobilizzazioniImmateriali",
    "B240":"CostiProduzioneAmmortamentiSvalutazioniAmmortamentoImmobilizzazioniImmateriali",
    "B241":"",
    "B242":"",
    "B243":"",
    "B244":"",
    "B245":"",
    "B246":"CostiProduzioneOneriDiversiGestione",
    "B250":"",
    "B251":"",
    "B252":"",
    "B267":"",
    "B268":"",
    "B257":"",
    "B270":"",
    "B259":"",
    "B260":"TotaleAttivoCircolante",
    "B269":"",
    "B265":"TotaleProventiOneriFinanziari",
    "B271":"UtilePerditaEsercizio",
    "B279":"",
    "B280":"",
    "B281":"TotaleAttivoCircolante",
    "B282":"",
    "B283":"TotaleProventiOneriFinanziari",
    "B284":"",
    "B291":"",
    "B287":"",
    "B288":"",
    "B295":"",
    "B296":"",

}

export const abbreviatoDA = {
    "B11" : "DatiAnagraficiDenominazione",
    "B13" : "",
    "B12" : "DatiAnagraficiCodiceCciaa",
    "B14" : "DatiAnagraficiSede",
    "B15" : "DatiAnagraficiPartitaIva",
    "B16" : "DatiAnagraficiCapitaleSociale",
    "B17" : "startDate",
    "B18" : "",
    "B19" : "CommentoNotaIntegrativa",
    "B20" : "",
    "B21" : "",
    "B22" : "",
    "B23" : "",
    "B24" : "TotaleDipendentiNumeroMedio",
    "B25" : "DatiAnagraficiAppartenenzaGruppo",
    "B26" : ""
}

export const abbreviatoB = {
    "B6":"",
    "B7":"CreditiVersoClientiTotaleCreditiVersoClienti",
    "B54":"",
    "B55":"",
    "B56":"",
    "B30":"ImmobilizzazioniImmaterialiAltre",
    "B52":"ImmobilizzazioniMaterialiAltriBeni",
    "B59":"",
    "B60":"",
    "B61":"",
    "B62":"",
    "B63":"",
    "B203":"",
    "B204":"",
    "B80":"",
    "B86":"CostiProduzioneMateriePrimeSussidiarieConsumoMerci",
    "B87":"ProdottiFinitiMerciVariazioneEsercizio",
    "B88":"",
    "B89":"RimanenzeProdottiFinitiMerci",
    "B90":"",
    "B117":"",
    "B118":"",
    "B119":"",
    "B120":"",
    "B121":"",
    "B122":"TotaleProventiOneriFinanziari",
    "B123":"",
    "B125":"DepositiBancariPostaliVariazioneEsercizio",
    "B126":"",
    "B127":"",
    "B129":"",
    "B130":"",
    "B133":"",
    "B134":"",
    "B135":"",
    "B136":"PatrimonioNettoRiservaLegale",
    "B137":"",
    "B138":"",
    "B140":"PossibilitaUtilizzazioneRiservaStraordinaria",
    "B141":"PatrimonioNettoCapitale",
    "B142":"",
    "B143":"",
    "B144":"",
    "B145":"",
    "B146":"",
    "B147":"",
    "B148":"",
    "B149":"",
    "B150":"",
    "B151":"",
    "B154":"",
    "B155":"",
    "B156":"",
    "B157":"",
    "B158":"TrattamentoFineRapportoLavoroSubordinato",
    "B206":"",
    "B207":"",
    "B209":"",
    "B211":"",
    "B212":"",
    "B213":"",
    "B214":"",
    "B216":"",
    "B217":"",
    "B218":"",
    "B219":"",
    "B221":"ValoreProduzioneRicaviVenditePrestazioni",
    "B222":"ValoreProduzioneVariazioniRimanenzeProdottiCorsoLavorazioneSemilavoratiFiniti",
    "B223":"",
    "B224":"IntroduzioneMovimentiImmobilizzazioniMateriali",
    "B226":"",
    "B227":"AccontiVariazioneEsercizio",
    "B229":"CostiProduzioneMateriePrimeSussidiarieConsumoMerci",
    "B230":"",
    "B231":"CostiProduzioneGodimentoBeniTerzi",
    "B233":"",
    "B234":"",
    "B235":"TrattamentoFineRapportoLavoroSubordinato",
    "B236":"",
    "B237":"",
    "B239":"TotaleImmobilizzazioniImmateriali",
    "B240":"TotaleImmobilizzazioniMateriali",
    "B241":"TotaleImmobilizzazioni",
    "B242":"IncrementoDecrementoDisponibilitaLiquide",
    "B243":"CostiProduzioneVariazioniRimanenzeMateriePrimeSussidiarieConsumoMerci",
    "B244":"",
    "B245":"",
    "B246":"CostiProduzioneOneriDiversiGestione",
    "B250":"",
    "B251":"",
    "B252":"",
    "B267":"",
    "B268":"",
    "B257":"DebitiAccontiTotaleAcconti",
    "B270":"",
    "B259":"TotaleImmobilizzazioni",
    "B260":"CommentoVariazioniCreditiIscrittiAttivoCircolante",
    "B269":"",
    "B265":"TotaleProventiOneriFinanziari",
    "B271":"UtilePerditaEsercizio",
    "B279":"",
    "B280":"IntroduzioneImmobilizzazioniFinanziarie",
    "B281":"CommentoVariazioniCreditiIscrittiAttivoCircolante",
    "B282":"",
    "B283":"TotaleProventiOneriFinanziari",
    "B284":"",
    "B291":"",
    "B287":"",
    "B288":"",
    "B295":"",
    "B296":""
}

export const ordinarioDA = {
    "B11" : "DatiAnagraficiDenominazione",
    "B13" : "",
    "B12" : "DatiAnagraficiCodiceCciaa",
    "B14" : "DatiAnagraficiSede",
    "B15" : "DatiAnagraficiPartitaIva",
    "B16" : "DatiAnagraficiCapitaleSociale",
    "B17" : "startDate",
    "B18" : "",
    "B19" : "CommentoNotaIntegrativa",
    "B20" : "",
    "B21" : "",
    "B22" : "",
    "B23" : "",
    "B24" : "TotaleDipendentiNumeroMedio",
    "B25" : "DatiAnagraficiAppartenenzaGruppo",
    "B26" : ""
}

export const ordinarioB = {
    "B6":"TotaleCreditiVersoSociVersamentiAncoraDovuti",
    "B7":"TotaleCreditiVersoSociVersamentiAncoraDovuti",
    "B54":"CostoCostiSviluppo",
    "B55":"AmmortamentiFondoAmmortamentoAvviamento",
    "B56":"",
    "B30":"CostoImmobilizzazioniImmaterialiCorsoAcconti",
    "B52":"CostoImmobilizzazioniMaterialiCorsoAcconti",
    "B59":"",
    "B60":"CostoPartecipazioniImpreseCollegate",
    "B61":"",
    "B62":"",
    "B63":"",
    "B203":"",
    "B204":"",
    "B80":"",
    "B86":"",
    "B87":"ProdottiFinitiMerciVariazioneEsercizio",
    "B88":"",
    "B89":"RimanenzeProdottiFinitiMerci",
    "B90":"",
    "B117":"CostoPartecipazioniImpreseCollegate",
    "B118":"CostoPartecipazioniImpreseCollegate",
    "B119":"CostoPartecipazioniImpreseCollegate",
    "B120":"",
    "B121":"CostoTotalePartecipazioni",
    "B122":"TotaleProventiOneriFinanziari",
    "B123":"",
    "B125":"DepositiBancariPostaliVariazioneEsercizio",
    "B126":"",
    "B127":"",
    "B129":"",
    "B130":"",
    "B133":"RimborsoCapitale",
    "B134":"PatrimonioNettoRiservaSoprapprezzoAzioni",
    "B135":"QuotaDisponibileRiserveRivalutazione",
    "B136":"PatrimonioNettoRiservaLegale",
    "B137":"PatrimonioNettoRiserveStatutarie",
    "B138":"PatrimonioNettoRiservaNegativaAzioniPropriePortafoglio",
    "B140":"QuotaDisponibileRiservaStraordinaria",
    "B141":"PatrimonioNettoCapitale",
    "B142":"",
    "B143":"",
    "B144":"",
    "B145":"",
    "B146":"PatrimonioNettoRiservaOperazioniCoperturaFlussiFinanziariAttesi",
    "B147":"",
    "B148":"",
    "B149":"",
    "B150":"",
    "B151":"PatrimonioNettoUtiliPerditePortatiNuovo",
    "B154":"FondiRischiOneriTrattamentoQuiescenzaObblighiSimili",
    "B155":"",
    "B156":"",
    "B157":"",
    "B158":"TrattamentoFineRapportoLavoroSubordinato",
    "B206":"",
    "B207":"",
    "B209":"",
    "B211":"",
    "B212":"",
    "B213":"",
    "B214":"",
    "B216":"",
    "B217":"",
    "B218":"",
    "B219":"",
    "B221":"ValoreProduzioneRicaviVenditePrestazioni",
    "B222":"",
    "B223":"",
    "B224":"CommentoImmobilizzazioniMateriali",
    "B226":"",
    "B227":"AccontiVariazioneEsercizio",
    "B229":"CostiProduzioneVariazioniRimanenzeMateriePrimeSussidiarieConsumoMerci",
    "B230":"",
    "B231":"CostiProduzioneGodimentoBeniTerzi",
    "B233":"",
    "B234":"RimborsoCapitale",
    "B235":"TrattamentoFineRapportoLavoroSubordinato",
    "B236":"FondiRischiOneriTrattamentoQuiescenzaObblighiSimili",
    "B237":"",
    "B239":"CommentoImmobilizzazioniImmateriali",
    "B240":"CommentoImmobilizzazioniMateriali",
    "B241":"IntroduzioneImmobilizzazioni",
    "B242":"IncrementoDecrementoDisponibilitaLiquide",
    "B243":"CostiProduzioneVariazioniRimanenzeMateriePrimeSussidiarieConsumoMerci",
    "B244":"",
    "B245":"CostiProduzioneAltriAccantonamenti",
    "B246":"CostiProduzioneOneriDiversiGestione",
    "B250":"",
    "B251":"CostoPartecipazioniImpreseCollegate",
    "B252":"",
    "B267":"",
    "B268":"CostoPartecipazioniImpreseCollegate",
    "B257":"DebitiAccontiTotaleAcconti",
    "B270":"",
    "B259":"TotaleImmobilizzazioni",
    "B260":"TotaleAttivoCircolante",
    "B269":"",
    "B265":"TotaleProventiOneriFinanziari",
    "B271":"UtilePerditaEsercizio",
    "B279":"CostoTotalePartecipazioni",
    "B280":"TotaleImmobilizzazioniFinanziarie",
    "B281":"TotaleAttivoCircolante",
    "B282":"",
    "B283":"TotaleProventiOneriFinanziari",
    "B284":"",
    "B291":"",
    "B287":"",
    "B288":"QuotaDisponibileRiservaStraordinaria",
    "B295":"",
    "B296":"",
}