
export const macroSettore = [
  "Agricoltura",
  "Industria",
  "Costruzioni",
  "Commercio",
  "Servizi",
  "Trasporti",
  "Sanità",
  "Pubblica Amministrazione",
  "Finanza e Assicurazioni",
  "Istruzione",
  "Turismo",
]

export const subSettore = [
  "Agricoltura",
    "Coltivazioni agricole",
    "Allevamento",
    "Silvicoltura",

  "Industria",
    "Industrie alimentari",
    "Industria metalmeccanica",
    "Industria chimica",
    "Industria tessile",

  "Costruzioni",
    "Edilizia residenziale",
    "Edilizia industriale",
    "Infrastrutture civili",

  "Commercio",
    "Commercio all’ingrosso",
    "Commercio al dettaglio",
    "Distribuzione automatica",

  "Servizi",
    "Servizi informatici",
    "Servizi di consulenza",
    "Servizi di pulizia",
    "Servizi di marketing",

  "Finanza e Assicurazioni",
    "Intermediazione finanziaria",
    "Compagnie assicurative",
    "Società di leasing",

  "Turismo",
    "Agenzie viaggi",
    "Tour operator",
    "Servizi di guida turistica",

  "Trasporti",
    "Trasporto merci",
    "Trasporto passeggeri",
    "Logistica e spedizioni",

  "Sanità",
    "Ospedali",
    "Studi medici",
    "Cliniche private",
    "Servizi di assistenza domiciliare",

  "Pubblica Amministrazione",
    "Amministrazioni comunali",
    "Enti regionali",
    "Uffici statali",
    "Servizi pubblici",

  "Istruzione",
    "Scuole primarie e secondarie",
    "Università e istituti superiori",
    "Formazione professionale",
    "Centri educativi privati"
];


export const settoreOptions = [
  "(A) Agricoltura, sivlicoltura e pesca",
  "(B) Estrazione",
  "(C) Manifattura",
  "(D) Produzione energia/gas",
  "(E) Fornitura acqua reti fognarie, rifiuti",
  "(D) Trasmissione energia/gas",
  "(F41) Costruzione di edifici",
  "(F42) Ingegneria civile",
  "(F43) Costruzioni specializzate",
  "(G45) Commercio autoveicoli",
  "(G46) Comm. Ingrosso",
  "(D) Distr. Energia/gas",
  "(G47) Commercio dettaglio",
  "(I56) Bar e ristoranti",
  "(H) Trasporto e magazzinaggio",
  "(I55) Hotel",
  "(JMN) Servizi alle imprese",
  "(PQRS) Servizi alle persone",
];

export const principaliBorse = [
  "Borsa Italiana - Euronext Milan (ex MTA)",
  "Euronext Growth Milan (ex AIM Italia)",
  "Mercato Telematico Azionario (MTA)",
  "NYSE - New York Stock Exchange",
  "NASDAQ",
  "AMEX - NYSE American",
  "LSE - London Stock Exchange",
  "AIM - Alternative Investment Market",
  "Frankfurter Wertpapierbörse (FWB) - Deutsche Börse / Xetra",
  "Euronext Paris",
  "BME - Bolsa de Madrid",
  "Euronext Amsterdam",
  "Euronext Bruxelles",
  "Euronext Lisbona",
  "SIX Swiss Exchange (Svizzera)",
  "Borsa di Toronto (TSX)",
  "Hong Kong Stock Exchange (HKEX)",
  "Tokyo Stock Exchange (TSE)",
  "Shanghai Stock Exchange (SSE)",
  "Shenzhen Stock Exchange (SZSE)",
  "Australian Securities Exchange (ASX)",
  "Singapore Exchange (SGX)",
  "Non quotata",
  "Delistata"
];

export const microSettore = [
  "Agricoltura",
    "Azienda agricola",
    "Azienda vitivinicola",
    "Azienda ortofrutticola",
    "Coltivazione biologica",
    "Coltivazione in serra",
    "Coltivazione cerealicola",
    "Azienda di allevamento bovino",
    "Azienda di allevamento avicolo",
    "Azienda apistica (produzione miele)",
    "Azienda di produzione latticini artigianali",
    "Coltivazione di piante aromatiche",
    "Coltivazione di piante officinali",
    "Agriturismo con produzione agricola propria",
    "Servizi agronomici e consulenze",
    "Servizi per irrigazione e attrezzature agricole",
  "Industria",
    "Produzione artigianale di mobili",
    "Produzione artigianale di gioielli",
    "Produzione artigianale di dolci",
    "Produzione industriale di alimenti",
    "Produzione industriale di materiali edili",
    "Produzione di componenti meccanici",
    "Produzione di articoli in plastica",
    "Produzione di materiali per edilizia",
    "Manutenzione impianti industriali",
    "Produzione di carta e imballaggi",
    "Industria metalmeccanica",
    "Industria chimica",
    "Industria tessile",
    "Industria calzaturiera",
    "Industria automobilistica e componentistica",
    "Produzione elettronica e schede PCB",
    "Industria farmaceutica",
    "Industria delle energie rinnovabili",
    "Industria tipografica e packaging",
    "Falegnameria industriale",
    "Laboratorio artigianale metallurgico",
  "Costruzioni",
    "Impresa edile",
    "Impresa di ristrutturazioni",
    "Impresa di movimento terra",
    "Società di noleggio attrezzature",
    "Installazione impianti fotovoltaici",
    "Impiantista elettrico",
    "Impiantista termoidraulico",
    "Montaggio e manutenzione ponteggi",
    "Imprese di carpenteria metallica",
    "Costruzione piscine e spa",
    "Rifacimento tetti e coperture",
    "Realizzazione impianti fognari",
    "Decoratori e pittori edili",
    "Posatori pavimenti e rivestimenti",
    "Imprese per isolamento termico e cappotto",
  "Commercio",
    "Commercio al dettaglio di abbigliamento",
    "Commercio al dettaglio di alimentari",
    "Commercio all'ingrosso di prodotti alimentari",
    "Commercio all'ingrosso di abbigliamento",
    "Supermercato",
    "Mini market",
    "Tabaccheria",
    "Cartoleria",
    "Libreria",
    "Erboristeria",
    "Farmacia",
    "Negozio di elettronica",
    "Negozio di informatica",
    "Negozio di animali",
    "Vendita prodotti per animali",
    "Negozio articoli per bambini",
    "Negozio articoli per la casa",
    "Negozio articoli sportivi",
    "Negozio di telefonia",
    "Riparazione telefoni",
    "Vendita online (e-commerce)",
    "Marketplace multi-brand",
  "Servizi",
    "Parrucchiere",
    "Estetista",
    "Centro estetico avanzato",
    "Centro benessere",
    "Studio di consulenza aziendale",
    "Studio di consulenza fiscale",
    "Studio di architettura",
    "Studio di ingegneria",
    "Studio legale",
    "Studio medico",
    "Studio dentistico",
    "Studio di fisioterapia",
    "Servizi di consulenza ambientale",
    "Servizi ingegneria ambientale",
    "Consulenza in energie rinnovabili",
    "Consulenza HR",
    "Agenzia interinale",
    "Servizi di traduzione",
    "Servizi fotografici",
    "Servizi video",
    "Organizzazione eventi",
    "Gestione sale conferenze",
    "Servizi di consulenza informatica",
    "Cybersecurity e protezione dati",
    "Servizi cloud computing",
    "Gestione server e hosting",
    "Call center",
    "Centro assistenza tecnica",
    "Servizi IT e networking",
    "Servizi di data entry",
    "Stampa digitale",
    "Centro copie",
    "Web agency",
    "Servizi di marketing digitale",
    "Servizi di grafica e stampa",
    "Tipografia",
    "Associazione culturale",
    "Attività di influencer marketing",
    "Creazione contenuti digitali",
    "Podcasting e servizi audio",
    "Servizi di contabilità esterna",
    "Gestione buste paga",
  "Finanza e Assicurazioni",
    "Consulenza finanziaria indipendente",
    "Agente assicurativo",
    "Broker assicurativo",
    "Società di factoring",
    "Società di leasing",
    "Intermediazione immobiliare per investimento",
    "Gestione patrimoniale",
    "Servizi di investimento e trading",
    "Studio di consulenza fiscale e tributaria",
    "Caf e centri assistenza fiscale",
    "Società di revisione contabile",
    "Servizi per dichiarazioni fiscali e 730",
  "Turismo",
    "Agenzia di viaggi",
    "Hotel",
    "Bed and Breakfast",
    "Affittacamere",
    "Centro sportivo",
    "Centro yoga",
    "Paninoteca",
    "Gelateria artigianale",
    "Pub",
    "Discoteca",
    "Ristorante",
    "Pizzeria",
    "Bar",
    "Attività di catering",
  "Trasporti",
    "Servizi di logistica",
    "Corriere espresso",
    "Magazzino conto terzi",
    "Azienda di trasporto merci",
    "Azienda di trasporto persone",
    "Autonoleggio",
    "Officina meccanica",
    "Officina autorizzata",
    "Autocarrozzeria",
    "Concessionaria auto",
    "Autoscuola",
  "Sanità",
    "Studio medico",
    "Studio dentistico",
    "Studio di fisioterapia",
    "Poliambulatorio privato",
    "Centro diagnostico e radiologico",
    "Ambulatorio veterinario",
    "Assistenza domiciliare anziani",
    "Centro diurno per disabili",
    "Ambulatorio infermieristico",
    "Studio di psicologia o psicoterapia",
    "Centro salute mentale",
    "Laboratorio analisi cliniche",
    "Farmacia galenica",
    "Studio ostetrico/ginecologico",
  "Pubblica Amministrazione",
    "Comune / Municipio",
    "Provincia / Città Metropolitana",
    "Regione",
    "Prefettura",
    "Questura",
    "Ufficio Anagrafe",
    "Ufficio Tecnico Comunale",
    "Ufficio Tributi",
    "Ufficio Protocollo",
    "Ufficio Lavori Pubblici",
    "Ufficio Urbanistica",
    "Ufficio Ambiente",
    "Azienda Sanitaria Locale (ASL)",
    "Azienda Ospedaliera Pubblica",
    "Istituto scolastico pubblico",
    "Università pubblica",
    "INPS / INAIL / Agenzia delle Entrate",
    "Centro per l’impiego",
    "Forze dell’Ordine (Polizia, Carabinieri, Guardia di Finanza)",
    "Vigili del Fuoco",
    "Polizia Locale / Municipale",
    "Tribunale / Procura della Repubblica",
    "Ufficio Giudiziario",
    "Archivio comunale / storico",
    "Biblioteca comunale",
    "Museo civico / pubblico",
    "Ente Parco o Riserva Naturale",
    "Consorzio pubblico",
    "Enti pubblici di ricerca",
    "Ufficio statistico comunale",
  "Istruzione",
    "Scuola privata",
    "Scuola pubblica (paritaria/convenzionata)",
    "Asilo nido privato",
    "Asilo nido comunale",
    "Scuola di lingua",
    "Scuola di musica",
    "Scuola di danza",
    "Scuola di teatro",
    "Centro di formazione professionale",
    "Centro studi universitari",
    "Istituto tecnico professionale",
    "Scuola guida teorica",
    "Tutoraggio e ripetizioni private",
    "Formazione e-learning",
    "Corsi di coding e tecnologia",
];